# Generated by Django 5.0.4 on 2025-02-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='complementary_hours',
            field=models.IntegerField(default=0),
        ),
    ]
