# Generated by Django 5.0.4 on 2025-02-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='complementary_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
