# Generated by Django 5.0.4 on 2025-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='hours_taken',
            field=models.IntegerField(default=0),
        ),
    ]
