# Generated by Django 5.1.6 on 2025-02-14 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0002_initial'),
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.student'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.coordinator'),
        ),
        migrations.AddField(
            model_name='complementaryhour',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementary_hours', to='events.event'),
        ),
        migrations.AddField(
            model_name='complementaryhour',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementary_hours', to='users.student'),
        ),
    ]
