# Generated by Django 5.0.4 on 2025-02-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_hours_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='hours_taken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
