# Generated by Django 5.1.6 on 2025-02-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issued_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='event',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='validated_by',
        ),
        migrations.AddField(
            model_name='certificate',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(default='certificates/default.pdf', upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='certificate',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ComplementaryHour',
        ),
    ]
