# Generated by Django 5.0.4 on 2025-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='complementary_hours_needed',
            field=models.IntegerField(default=0),
        ),
    ]
